@hostname = localhost
@port = 8080
@scheme=http
@baseURL={{scheme}}://{{hostname}}:{{port}}
@table=Table_1
@primaryKey=1

### status
GET {{baseURL}}/rest/

### info
GET {{baseURL}}/rest/$info

### catalog
GET {{baseURL}}/rest/$catalog

### catalog all
GET {{baseURL}}/rest/$catalog/$all

### catalog @table
GET {{baseURL}}/rest/$catalog/{{table}}

### get @table data : /rest/NameOfTheDataclass
GET {{baseURL}}/rest/{{table}}

### create or update @table entity: /rest/NameOfTheDataclass
POST {{baseURL}}/rest/{{table}}

{
    "ID": {{primaryKey}}
}

### delete @table entity: /rest/NameOfTheDataclass
POST {{baseURL}}/rest/{{table}}({{primaryKey}}?$method=delete
